/// Flutter icons Bootybuilder
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Bootybuilder
///      fonts:
///       - asset: fonts/Bootybuilder.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Bootybuilder {
  Bootybuilder._();

  static const _kFontFam = 'Bootybuilder';
  static const _kFontPkg = null;

  static const IconData about = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData categories = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData myworkout = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData workouts = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
